### ISSUE TITLE
It dosen't work when using a subset gene files?

### ISSUE THREAD

**Issue by SeqCrafter** [jluebeck/CycleViz#13]
in my yaml file, I writed:
gene_subset_file: "gens.txt"

and in my gens.txt is:
CCND1
CCND3
GAB2
GLO1
INTS4
KDM2A
PAK1
RBM14
RSF1
TFEB

But it still plot lots of genes, the subset seems not working.

**Comment by jluebeck** [comment]
Hi Xiaoguang, 

Thanks for catching this - looks like if `gene_subset_file` was specified to the .yaml the argument was given a wrong name and would not be used. I have fixed it and tested in the latest update. Please pull the latest version and let me know if you encounter any other issues.

Thanks,
Jens

**Comment by SeqCrafter** [comment]
> Hi Xiaoguang,
> 
> Thanks for catching this - looks like if `gene_subset_file` was specified to the .yaml the argument was given a wrong name and would not be used. I have fixed it and tested in the latest update. Please pull the latest version and let me know if you encounter any other issues.
> 
> Thanks, Jens

Sorry for my mistake; I didn't give the wrong name in my yaml file; it's because I wrongly wrote it at this issue. In addition, I also use the latest version, but the problem still presents itself.

**Comment by jluebeck** [comment]
Hi Xiaoguang, 

Can you please provide the yaml file in question? Even better, would be to also include the graph and cycles files too? I would be happy to try and reproduce this issue locally. I did not encounter it in my own local tests unfortunately. Feel free to email the relevant files to me at jluebeck [at] ucsd. edu if needed.

Thanks,
Jens

**Comment by SeqCrafter** [comment]
[test.zip](https://github.com/AmpliconSuite/CycleViz/files/11673847/test.zip)

**Comment by jluebeck** [comment]
Hi, apologies, it looks like the last change I made was to the jluebeck fork, not the AmpliconSuite/CycleViz repo. Can you please try pulling the latest version again? When I try your files now it appears to work as expected. Sorry again for the confusion.

**Comment by SeqCrafter** [comment]
> Hi, apologies, it looks like the last change I made was to the jluebeck fork, not the AmpliconSuite/CycleViz repo. Can you please try pulling the latest version again? When I try your files now it appears to work as expected. Sorry again for the confusion.

Thank you so much, now it worked.
